[wip] Cleanup build script, use XCFramework
Sjors/libwally-swift pull request #61
Opened 2022-04-09 05:27 UTC by jurvis

**This PR is still a work in progress!**

## Purpose
This PR primarily does a few things:
1. Support latest `libtool@2.4.7` change which will require a PR merge in `libwally-core` (https://github.com/ElementsProject/libwally-core/pull/321)2. 
2. Support running in iOS simulator on M1 Macs

## Implementation
To achieve 1, I noticed that the latest `libwally-core` change no longer includes `libsecp256k1` symbols inside the `libwally-core.a` library. To keep this simple, I imported `libsecp256k1.a` from `CLibWally/libwally-core/src/secp256k1/.libs` to the Xcode project

To achieve 2, we will have to build an `xcodebuild -xcframework` instead of using the previous `lipo` build command. This is because M1 macs use `arm64` as an architecture for iOS simulator, which will conflict in a fat binary since an iOS simulator's `arm64` arch is undifferentiated from an iOS device's `arm64` arch.

## Testing Notes
- [ ] Cocoapods Install
- [ ] Carthage script update (?)

## Follow-up
- Add Swift Package Manager support (?)
- Now that we use xcframeworks, we can probably support Mac Catalyst too (https://github.com/Sjors/libwally-swift/issues/41)

2022-04-09 05:33 UTC, jurvis commented
@Sjors putting this PR up so you can track my progress with this. 

Right now, I've gotten `build-libwally.sh` to spit out an xcframework for device-only, simulator-only, or both (with https://github.com/ElementsProject/libwally-core/pull/321/commits/59652b58b26adc7cbc290010833a2bca3b848b42 checked out as `libwally-core`)

Over the coming days I'll test it with Carthage/Cocoapods. Once that's done, you're OK with these changes, and https://github.com/ElementsProject/libwally-core/pull/321 is merged, we can put out a release and everything should work again!

2022-04-13 12:47 UTC, Sjors commented
Thanks! This all sounds great, I'll give it a review soon(tm); I'm just back from the Miami conference, so a bit behind on ... everything. First thing I'll do is bump the libwally-core version, so you can rebase on that.

2022-04-13 14:14 UTC, Sjors requested changes
This is a really nice cleanup! I'll test once you had a chance to rebase.

2022-04-13 14:14 UTC, Sjors commented on LibWally.podspec
> -                               'SWIFT_WHOLE_MODULE_OPTIMIZATION' => 'YES',
de7ecc93978b254e20bd388d72d5d04de5c6aa4e Why the removal? Is it deprecated? Useless?

2022-04-13 14:14 UTC, Sjors commented on LibWally.podspec
> +  spec.version      = "0.0.7"
188794c29502531a8a6396c45d82bc71dbd40170: no need to bump the version when you're trying this. You can point to a branch, see e.g. https://github.com/Sjors/nthkey-ios/pull/69/commits/ecf25135ea7d28416efd1cfb04f88b16786583d8

I'll try to remember to bump this version next time I tag a release though.

2022-04-13 14:14 UTC, Sjors commented on LibWally.podspec
> +  spec.source       = { :git => "https://github.com/jurvis/libwally-swift.git", :tag => "v#{spec.version}", :submodules => true  }
60ed50a7c9f415166c413d3d215caf835ec43f75: don't forget to drop this. Also, I wonder if you really need that in order to test a fork.

2022-04-13 15:21 UTC, jurvis commented on build-libwally.sh
> +    ./configure --disable-shared --host=aarch64-apple-darwin --enable-static --disable-elements
good catch, it probably won't. I just hard-coded it for now and can fix it later 😄

2022-04-13 15:23 UTC, jurvis commented on build-libwally.sh
> +    export CXXFLAGS="-O3 -arch arm64 -fembed-bitcode -mios-version-min=11.0 -isysroot `xcrun -sdk iphoneos --show-sdk-path`"
think it will be nice to keep it at a generous minimum version, since developers may want to support them

2022-04-13 15:24 UTC, jurvis commented on LibWally.podspec
> -                               'SWIFT_WHOLE_MODULE_OPTIMIZATION' => 'YES',
oh, ignore all the diffs in `podspec` for now. This has turned into kind of a working branch for me to test Cocoapods like a monkey and figuring out how it all comes together 😅

2022-04-13 15:25 UTC, jurvis commented on LibWally.podspec
> +  spec.source       = { :git => "https://github.com/jurvis/libwally-swift.git", :tag => "v#{spec.version}", :submodules => true  }
I did this to test `pod spec lint LibWally.podspec` since it'll the information defined at `spec.source` and do it's work.

2022-04-13 15:37 UTC, Sjors commented
If it makes things easier (see https://github.com/Sjors/libwally-swift/pull/62#issuecomment-1098175785) feel free to create a separate PR that cherry-picks some commits from here.

2022-04-14 22:44 UTC, jurvis commented
@Sjors sorry I need some time to catch up on some school deadlines over the next couple of days. hoping to get this done by this weekend 😄

2022-04-15 00:19 UTC, closed without merging

2022-04-15 08:19 UTC, Sjors commented
Take your time!

By the way, it should be possible to just force push, rather than open a new PR.

2022-04-15 13:45 UTC, jurvis commented
@Sjors oh, yeah. Not sure why I didn’t think of that. Must’ve been late 😅